version: '3.8'

services:
  docker-education-repo:
    build:
      context: ./docker-education-repo
      dockerfile: Dockerfile
    ports:
      - "2023:80"
    networks:
      - dcs-bank
    volumes:
      - ./docker-education-repo-service/appsettings.json:/publish/appsettings.json

  api-gateway-service:
    image: nickholas/dcs-api-gateway:latest
    networks:
      - dcs-bank
    depends_on:
      - docker-education-repo
    ports:
      - "2100:2100"
    volumes:
      - ./api-gateway-service/appsettings.json:/app/appsettings.json

  decision-maker-service:
    image: nickholas/dcs-decision-maker-service:latest
    networks:
      - dcs-bank
    volumes:
      - ./decision-maker-service/appsettings.json:/app/appsettings.json

  emailing-service:
    image: nickholas/dcs-emailing-service:latest
    networks:
      - dcs-bank
    volumes:
      - ./emailing-service/appsettings.json:/app/appsettings.json

networks:
  dcs-bank:
    driver: bridge
